Add unchecked variants to CachedRegex and CachedRegexBuilder + general housekeeping
1aim/rust-regex-cache pull request #2
Opened 2020-10-15 14:46 UTC by yannleretaille

@meh would be great if you could review this!

2020-10-15 15:41 UTC, meh requested changes
Looks good otherwise.

Can you also use the same commit format as the rest please? (semantic commit messages)

2020-10-15 15:41 UTC, meh commented on src/cache.rs
>  		Ok(CachedRegex::from(CachedRegexBuilder::new(cache, source)))
Could you use `new_unchecked` here?

2020-10-15 16:12 UTC, yannleretaille commented on src/cache.rs
>  		Ok(CachedRegex::from(CachedRegexBuilder::new(cache, source)))
why? the syntax check for `CachedRegexBuilder` only happens in ` CachedRegexBuilder::build`, not in `CachedRegexBuilder::new`

2020-10-15 16:17 UTC, yannleretaille commented
now using semantic commit messages!

2020-10-16 22:40 UTC, merged

2020-10-16 22:42 UTC, meh commented
Thank you for your valuable contribution!